### ISSUE TITLE
Since Update 1.4 it's not working anymore for VS 2013 and 2012

### ISSUE THREAD

**Issue by 0x084E** [ctlajoie/DupSelection#7]
Hello,

as the title says, no error or anything else, it just does nothing...
Could you please have a look, I'm feeling like half a developer without it ;)

Thanks in advance

**Comment by ctlajoie** [comment]
I have tried several things in order to try to duplicate this problem but no matter how I install it, it "just works". When you go into the VS Keyboard options, does the Edit.DuplicateSelection command show up in the list? Perhaps something is preventing the extension from loading at all...

**Comment by 0x084E** [comment]
Command shows up and is bound to shortcut Ctrl+D in Text Editor (Alt+D doesn't work either).
Do you have a compiled Version 1.3? If I downgrade and it is working again I would have a look at the differences between 1.3 and 1.4. Maybe I can find the cause then.

**Comment by ctlajoie** [comment]
I didn't save that version but I think I can scrape some files from various places to build a vsix with 1.3 in it. I'll let you know when it's ready.

There were actually no code changes between 1.3 and 1.4. I compiled version 1.3 using VS2010 a long time ago and I no longer have VS2010, so I opened the solution in VS2012 and some automated process made modifications to the project file and the DupSelection.vsct file (which defines the Edit.DuplicateSelection command and determines where to place the item in the edit menu).
One other thing I had to change in order to get it to compile, was that I had to switch to .NET 4.5 (instead of 4.0). IDK if this is relevant but it could be a clue...

**Comment by ctlajoie** [comment]
[DupSelection-1.3.vsix](https://www.dropbox.com/s/h1spdtqfspvg7ev/DupSelection-1.3.vsix?dl=0)

**Comment by 0x084E** [comment]
Thanks, this one works! But if I update to 1.4 it breaks again. Really strange...
I'll try to compile it by myself tomorrow and see if I can find anything.

**Comment by ctlajoie** [comment]
When I was building that vsix for you I realized that to add VS2015 support I really didn't need to rebuild the extension at all, I just had to modify the .vsixmanifest file inside the vsix file (which is really just a zip file). I uploaded a new version (1.5) that uses same binary as 1.3 but adds VS2015 support. Can you verify that this new version also works?

**Comment by 0x084E** [comment]
Yes, 1.5 works!

**Comment by ctlajoie** [comment]
Great, thanks!
